//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phumla_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingEnquiry
    {
        public string enquiryID { get; set; }
        public string custID { get; set; }
        public string Details { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
