//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phumla_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeBooking
    {
        public string changeID { get; set; }
        public string bookingID { get; set; }
        public System.DateTime Date { get; set; }
        public string Details { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
