//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phumla_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confirmation
    {
        public string confirmationID { get; set; }
        public string hotelID { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
